/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Sara
 */
public class vPartida extends javax.swing.JFrame {

    /**
     * Creates new form vPartida
     */
    public vPartida() {
        setTitle("Partida de tejo");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalirP = new javax.swing.JButton();
        btnLanzartejo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 34)); // NOI18N
        jLabel2.setText("CAMPEONATO NACIONAL DE TEJO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        btnSalirP.setBackground(new java.awt.Color(255, 255, 153));
        btnSalirP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalirP.setText("SALIR");
        jPanel1.add(btnSalirP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 100, 40));

        btnLanzartejo.setBackground(new java.awt.Color(255, 153, 153));
        btnLanzartejo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLanzartejo.setText("LANZAR TEJO");
        jPanel1.add(btnLanzartejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventanapartida.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLanzartejo;
    public javax.swing.JButton btnSalirP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public void mostrarMensaje(String m){
        JOptionPane.showMessageDialog(null, m, "Info", ABORT);
    }
}
